using System.IO.MemoryMappedFiles;
using System.Runtime.InteropServices;
using System.Text;
using IpcAdapter;
using IpcAdapter.Encoders;
using IpcAdapter.Events;
using Logger;

namespace SharedMemoryAdapter;

public class TwoWayBuffer : IIpcAdapter {
    public const string POSIX_SHARED_MEMORY_PATH = "/dev/shm/";
    public const char MESSAGE_DELIMETER = ';';
    
    public bool IsConnected { get; private set; }
    public event Action<Event>? ReceivedEventEvent;

    private string _memoryName;
    private int _memorySize;
    
    private MemoryMappedFile? _mappedMemory;
    private CircularBuffer? _consumingBuffer;
    private CircularBuffer? _producingBuffer;

    private IEncoder _encoder;
    private ILogger? _logger;

    public TwoWayBuffer(string name, int pages, IEncoder encoder, ILogger? logger = null) {
        _encoder = encoder;
        _logger = logger;
        _memoryName = name;
        _memorySize = 2 * pages * Environment.SystemPageSize;
    }
    
    public void SendEvent(Event @event) {
        string message = _encoder.EncodeEvent(@event);
        if (!_producingBuffer!.Write(message + MESSAGE_DELIMETER)) {
            _logger?.LogError("Could not write to shared memory buffer, not enough available space.");
            // TODO: Pause producer
        }
        else {
            _logger?.LogDebug("Written message to producer buffer: " + message);
        }
    }

    public Task<bool> TryConnectAsync() => Task.Run(TryConnect);

    private bool TryConnect() {
        try {
            _mappedMemory = OpenSharedMemory(_memoryName);
            _consumingBuffer = new CircularBuffer(_mappedMemory, 0, _memorySize / 2);
            _producingBuffer = new CircularBuffer(_mappedMemory, _memorySize / 2, _memorySize / 2);
    
            _ = Task.Run(ListenForRemoteEvents);
            IsConnected = true;
            _logger?.LogInfo("Successfully connected to simulator's shared memory buffer.");
            return true;
        }
        catch (Exception e) {
            _logger?.LogError("Error during shared memory intialization: " + e.Message);
            return false;
        }
    }

    public void Disconnect() {
        _mappedMemory = null;
        IsConnected = false;
        _logger?.LogWarning("Disconnected from shared memory.");
    }

    private MemoryMappedFile OpenSharedMemory(string name) {
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows)) {
            string appdataPath = Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData);
            string boostInterprocessPath = Path.Combine(appdataPath, "boost_interprocess");
            string mappedFile = Directory.EnumerateFiles(boostInterprocessPath, name, SearchOption.AllDirectories).First();
            
            // Generated by Gemini to solve "Used by another process error"
            var fileStream = new FileStream(mappedFile, FileMode.Open, FileAccess.ReadWrite, FileShare.ReadWrite);
            return MemoryMappedFile.CreateFromFile(fileStream,null,0,
                MemoryMappedFileAccess.ReadWrite, HandleInheritability.None, false);
            // End of generated code
        }
        else { // POSIX
            return MemoryMappedFile.CreateFromFile(POSIX_SHARED_MEMORY_PATH + name, FileMode.Open);
        }
    }

    private void ListenForRemoteEvents() {
        try {
            // TODO: Use IPC semaphore
            while (IsConnected) {
                if (_consumingBuffer!.IsEmpty) continue;

                byte[]? data = _consumingBuffer.ConsumeUntil((byte)MESSAGE_DELIMETER);
                if (data == null) {
                    _logger?.LogError("A span of incoming message could not be determined, skipping.");
                    continue;
                }

                string message = Encoding.ASCII.GetString(data)[..^1]; // strip delimeter at the end
                _logger?.LogDebug("Read message from the consumer buffer: " + message);
                
                if (!_encoder.TryDecodeEvent(message, out Event @event)) {
                    _logger?.LogError("Failed to decode message: " + message);
                    continue;
                }

                ReceivedEventEvent?.Invoke(@event);
            }
        }
        catch (Exception e) {
            _logger?.LogError("Consuming messages from shared memory buffer failed: " + e.Message);
        }
    }
}