:: Generated by Gemini - Convert preprocess.sh to equivalent batch script

@echo off
:: Enable local variable scope and strict error checking
setlocal EnableExtensions EnableDelayedExpansion

:: Check if the sketch directory argument was provided (set -u equivalent)
if "%~1"=="" (
    echo Error: Missing sketch directory argument.
    exit /b 1
)

set "SKETCH_DIR=%~1"

:: Set destination directory; default to .\backend\executable\sketch if %2 is empty
if "%~2" == "" (
    set "DESTINATION_DIR=.\backend\executable\sketch"
) else (
    set "DESTINATION_DIR=%~2\sketch"
)

set "TARGET_FILE=%DESTINATION_DIR%\sketch.cpp"

:: Create destination directory if it doesn't exist
if not exist "%DESTINATION_DIR%" (
    mkdir "%DESTINATION_DIR%" || exit /b 1
)

:: Copy sketch directory files to the destination
copy /Y "%SKETCH_DIR%\*" "%DESTINATION_DIR%\" >nul || exit /b 1

:: Compile/Preprocess with arduino-cli
arduino-cli compile -b arduino:avr:uno --preprocess "%SKETCH_DIR%" > "%TARGET_FILE%" || exit /b 1

:: Remove temporary .ino files in the destination directory
if exist "%DESTINATION_DIR%\*.ino" (
    del /Q "%DESTINATION_DIR%\*.ino" || exit /b 1
)

echo Preprocessing successful
:: Resolve and display the absolute path (realpath equivalent)
for %%I in ("%TARGET_FILE%") do echo %%~fI created

endlocal

:: End of generated code