#ifndef ARGUINO_PROGRAMOPTIONS_HPP
#define ARGUINO_PROGRAMOPTIONS_HPP

#include <boost/program_options.hpp>
#include <iostream>

namespace po = boost::program_options;

struct ProgramOptions {
    std::string SimulatorLogPath;
    logger::LogLevel Verbosity;

    // TCP implementation
    std::string TcpLogPath;
    int TcpPort;

    // Shared memory implementation
    std::string ShmemName;
    int ShmemSizePages;
};

static po::options_description create_common_options()
{
    po::options_description description("Common options");

    description.add_options()                                                      //
        ("help,h",                                                                 //
            "Print this help message")                                             //
        ("log-simulator",                                                          //
            po::value<std::string>()->default_value("./core.log"),                 //
            "Path to the log file for simulator events")                           //
        ("verbosity,v",                                                            //
            po::value<logger::LogLevel>()->default_value(logger::LogLevel::Info),  //
            "Verbosity of used loggers");

    return description;
}

static po::options_description create_tcp_options()
{
    po::options_description description("TCP options");

    description.add_options()                                           //
        ("port,p",                                                      //
            po::value<int>()->default_value(8888),                      //
            "Port on which to launch TCP server")                       //
        ("log-tcp",                                                     //
            po::value<std::string>()->default_value("./core_tcp.log"),  //
            "Path to the log file for TCP events");                     //

    return description;
}

static po::options_description create_shmem_options()
{
    po::options_description description("Shared memory options");

    description.add_options()                                                       //
        ("shmem-name,n",                                                            //
            po::value<std::string>()->default_value("Arguino-ipc"),                 //
            "Name of the shared memory segment")                                    //
        ("shmem-size,s",                                                            //
            po::value<int>()->default_value(1024),                                  //
            "Size of each of the write and read shared memory segments in pages");  //

    return description;
}

inline ProgramOptions parse_arguments(int argc, char** argv)
{
    po::options_description description("Command line options");
    description.add(create_common_options());

#ifdef ARGUINO_TCP
    description.add(create_tcp_options());
#endif
#ifdef ARGUINO_SHARED_MEMORY
    description.add(create_shmem_options());
#endif

    po::variables_map variables;
    po::store(po::parse_command_line(argc, argv, description), variables);
    po::notify(variables);

    if (variables.count("help")) {
        std::cout << description << std::endl;
        exit(1);
    }

    ProgramOptions options;
    options.SimulatorLogPath = variables["log-simulator"].as<std::string>();
    options.Verbosity = variables["verbosity"].as<logger::LogLevel>();

#ifdef ARGUINO_TCP
    options.TcpPort = variables["port"].as<int>();
    options.TcpLogPath = variables["log-tcp"].as<std::string>();
#endif
#ifdef ARGUINO_SHARED_MEMORY
    options.ShmemName = variables["shmem-name"].as<std::string>();
    options.ShmemSizePages = variables["shmem-size"].as<int>();
#endif

    return options;
}

// Generated by Gemini, prompted to support po for LogLevel enum
namespace logger {

inline std::istream& operator>>(std::istream& in, LogLevel& level)
{
    std::string token;
    in >> token;
    if (token == "Debug")
        level = LogLevel::Debug;
    else if (token == "Info")
        level = LogLevel::Info;
    else if (token == "Warning")
        level = LogLevel::Warning;
    else if (token == "Error")
        level = LogLevel::Error;
    else {
        in.setstate(std::ios::failbit);
        throw boost::program_options::validation_error(
            boost::program_options::validation_error::invalid_option_value);
    }
    return in;
}

inline std::ostream& operator<<(std::ostream& out, const LogLevel& level)
{
    if (level == LogLevel::Debug) out << "Debug";
    if (level == LogLevel::Info) out << "Info";
    if (level == LogLevel::Warning) out << "Debug";
    if (level == LogLevel::Error) out << "Error";

    return out;
}

}  // namespace logger

#endif